name: 😋 我找到了新的可用源！
description: 为大家分享新的可用源！
title: "[New Source] "
labels: ['源']
body:
  - type: markdown
    attributes:
      value: |
        感谢你的分享！这将使你与更广大的用户得到更多可选的服务！

  - type: textarea
    id: description
    attributes:
      label: 描述该源
      description: |
        1. 请告诉我们提供该源的镜像站的主体URL
        2. 你是否已经测试过该源的可用性？
    validations:
      required: true
